services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: insightai-backend
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "8000:8000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: insightai-frontend
    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - backend