import sqlglot
from sqlalchemy import text
from sqlglot import expressions as exp
from app.database.session import SessionLocal
from app.schemas.validation import SQLValidationResult, ValidationCheck
from app.config.logging import get_logger

logger = get_logger(__name__)

def validate_syntax(generated_sql: str) -> exp.Expression:
    """
    Parse SQL into an Abstract Syntax Tree (AST).
    Raises an exception if the SQL is invalid.
    """

    return sqlglot.parse_one(
        generated_sql,
        dialect="postgres"
    )

    

def validate_read_only(expression: exp.Expression) -> SQLValidationResult:
    """
    Ensure that only read only SQL statements are allowed.
    """

    if not isinstance(expression, exp.Select):
        return SQLValidationResult(
            is_valid=False,
            failed_Check=ValidationCheck.READ_ONLY,
            error_message="Only SELECT statements are allowed."
        )

    return SQLValidationResult(
        is_valid=True
    )

def validate_schema(expression: exp.Expression, schema: dict[str, list[str]]) -> SQLValidationResult:
    """
    Validate that all referenced tables exist in the database schema.
    """

    tables = {
        table.name
        for table in expression.find_all(exp.Table)
    }

    available_tables = set(schema.keys())

    invalid_tables = tables - available_tables

    if invalid_tables:
        return SQLValidationResult(
            is_valid=False,
            failed_Check=ValidationCheck.SCHEMA,
            error_message=(
                f"Unknown table(s): {', '.join(sorted(invalid_tables))}"
            )
        )

    return SQLValidationResult(
        is_valid=True
    )

def validate_execution(generated_sql: str) -> SQLValidationResult:
    """
    Validate that postgresSQL can successfully plan the query.
    """

    session = SessionLocal()

    try:
        session.execute(
            text(f"Explain {generated_sql}")
        )

        return SQLValidationResult(
            is_valid=True
        )

    except Exception as e:

        return SQLValidationResult(
            is_valid=False,
            failed_Check=ValidationCheck.EXECUTION,
            error_message=str(e)
        )

    finally:
        session.close()


def validate_sql(generated_sql: str, schema: dict[str, list[str]]) -> SQLValidationResult:
    """
    Validate the sql before execution.
    """

    logger.info("SQL validation tool started")

    # if not generated_sql:
    #     return SQLValidationResult(
    #         is_valid=False,
    #         failed_check=ValidationCheck.SYNTAX,
    #         error_message="No SQL was generated by the LLM."
    #     )

    try:
        expression = validate_syntax(generated_sql)
    except sqlglot.errors.ParseError as e:
        logger.warning("SQL syntax validation failed")

        return SQLValidationResult(
            is_valid=False,
            failed_Check=ValidationCheck.SYNTAX,
            error_message=str(e)
        )

    result = validate_read_only(expression)
    if not result.is_valid:
        logger.warning("SQL read-only validation failed")
        return result

    result = validate_schema(expression, schema)
    if not result.is_valid:
        logger.warning("SQL schema validation failed")
        return result
    
    result = validate_execution(generated_sql)
    if not result.is_valid:
        logger.warning("SQL execution validation failed")
        return result

    logger.info("All SQL validation checks passed")

    return SQLValidationResult(
        is_valid=True
    )